[workspace]
members = [
    "./crates/mltt-cli",
    "./crates/mltt-concrete",
    "./crates/mltt-core",
    "./crates/mltt-parse",
    "./crates/mltt-span",
    "./crates/mltt-test",
    "./crates/mltt-test-harness",
]
