[package]
name = "mltt-test-generate"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
license = "MIT"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
heck = "0.3.1"
