[package]
name = "mltt-core"
version = "0.1.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "The core type theory of the MLTT language"
license = "MIT"
edition = "2018"
publish = false

[dependencies]
im = "12.2.0"
log = "0.4"
pretty = "0.5.2"
